const categoryTranslations: Record<string, string> = {
  "Same person transfer": "Transferência entre contas",
  "Transfer - PIX": "Transferência - PIX",
  "Transfer": "Transferência",
  "Wire transfer": "Transferência bancária",
  "Digital services": "Serviços digitais",
  "Services": "Serviços",
  "Food": "Alimentação",
  "Restaurants": "Restaurantes",
  "Groceries": "Supermercado",
  "Health": "Saúde",
  "Education": "Educação",
  "Transportation": "Transporte",
  "Shopping": "Compras",
  "Entertainment": "Entretenimento",
  "Travel": "Viagem",
  "Taxes": "Impostos",
  "Loans": "Empréstimos",
  "Investments": "Investimentos",
  "Bills": "Contas a pagar",
  "Utilities": "Utilidades",
  "Home": "Moradia",
  "Rent": "Aluguel",
  "Salary": "Salário",
  "Insurance": "Seguro",
  "Subscriptions": "Assinaturas",
  "Personal care": "Cuidados pessoais",
  "Pets": "Animais de estimação",
  "Gifts": "Presentes",
  "Government": "Governo",
  "Electronics": "Eletrônicos",
  "Clothing": "Vestuário",
  "Gas": "Combustível",
  "Telecommunications": "Telecomunicações",
  "Financial charges": "Encargos financeiros",
  "Interest": "Juros",
  "Cash": "Dinheiro",
  "ATM": "Caixa eletrônico",
  "Payment": "Pagamento",
  "Credit card payment": "Pagamento de cartão",
  "Credit card": "Cartão de crédito",
  "Uncategorized": "Sem categoria",
  "Other": "Outros",
  "Pension": "Previdência",
  "Donations": "Doações",
  "Rewards": "Recompensas",
  "Refund": "Reembolso",
  "Deposit": "Depósito",
  "Withdrawal": "Saque",
  "Fee": "Taxa",
  "Subscription": "Assinatura",
  "Online payment": "Pagamento online",
  "Transfer - TED": "Transferência - TED",
  "Transfer - DOC": "Transferência - DOC",
}

export function translateCategory(category: string): string {
  return categoryTranslations[category] ?? category
}
